name       : haskell-case-insensitive
version    : 1.2.0.11
release    : 4
source     :
    - https://hackage.haskell.org/package/case-insensitive-1.2.0.11/case-insensitive-1.2.0.11.tar.gz : a7ce6d17e50caaa0f19ad8e67361499022860554c521b1e57993759da3eb37e3
license    : BSD-3-Clause
component  : programming.haskell
summary    : The module Data.CaseInsensitive provides the CI type constructor which can be parameterised by a string-like type
description: |
    The module Data.CaseInsensitive provides the CI type constructor which can be parameterised by a string-like type
builddeps  :
    - haskell-cabal-install
    - haskell-hashable
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
