name       : haskell-case-insensitive
version    : 1.2.0.7
release    : 2
source     :
    - http://hackage.haskell.org/package/case-insensitive-1.2.0.7/case-insensitive-1.2.0.7.tar.gz : 160d3898fd0d8b50bed820ff633e6292438f069adec5267c42b8bcf0f386cac8
license    : BSD-3-Clause
component  : programming.haskell
summary    : The module Data.CaseInsensitive provides the CI type constructor which
    can be parameterised by a string-like type
description: |
    The module Data.CaseInsensitive provides the CI type constructor which can be parameterised by a string-like type
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-hashable
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
