name       : haskell-case-insensitive
version    : 1.2.0.7
release    : 1
source     :
    - http://hackage.haskell.org/package/case-insensitive-1.2.0.7/case-insensitive-1.2.0.7.tar.gz : 160d3898fd0d8b50bed820ff633e6292438f069adec5267c42b8bcf0f386cac8
license    : BSD-3-Clause
component  : programming
summary    : The module Data.CaseInsensitive provides the CI type constructor which can be parameterised by a string-like type
description: |
    The module Data.CaseInsensitive provides the CI type constructor which can be parameterised by a string-like type
builddeps  :
    - ghc
    - haskell-hashable
    - haskell-text
setup      : |
    sudo ghc-pkg recache
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 case-insensitive-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/case-insensitive-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/case-insensitive-$version/*.a
