name       : haskell-case-insensitive
version    : 1.2.1.0
release    : 5
source     :
    - https://hackage.haskell.org/package/case-insensitive-1.2.1.0/case-insensitive-1.2.1.0.tar.gz : 296dc17e0c5f3dfb3d82ced83e4c9c44c338ecde749b278b6eae512f1d04e406
license    : BSD-3-Clause
component  : programming.haskell
summary    : The module Data.CaseInsensitive provides the CI type constructor which can be parameterised by a string-like type
description: |
    The module Data.CaseInsensitive provides the CI type constructor which can be parameterised by a string-like type
builddeps  :
    - haskell-cabal-install
    - haskell-hashable-devel
rundeps    :
    - devel:
        - haskell-hashable-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
